### ISSUE TITLE
Need your Nostr pubkey

### ISSUE THREAD

**Issue by blakejakopovic** [supertestnet/superstore#1]
Hey, I shared your project on Nostr, and it was well received. Very cool project. I’ve indirectly received some sats (Nostr ZAPs) I’d like to forward onto you. Can you share with me a lightning address?

Here is my Nostr for DM if preferred. 
npub1ktw5qzt7f5ztrft0kwm9lsw34tef9xknplvy936ddzuepp6yf9dsjrmrvj

**Comment by supertestnet** [comment]
Hi Blake, thanks! My nostr pubkey is npub1yxp7j36cfqws7yj0hkfu2mx25308u4zua6ud22zglxp98ayhh96s8c399s
