### ISSUE TITLE
Bug when checking out with "Let users set the price" option

### ISSUE THREAD

**Issue by NEEDcreations** [supertestnet/superstore#11]
See pictures
![screenshot-magicwebstore xyz-2023 08 16-00_07_39](https://github.com/supertestnet/superstore/assets/142443937/44bf8d85-af05-437c-a6fd-d79ca444d028)
![screenshot-magicwebstore xyz-2023 08 16-00_07_27](https://github.com/supertestnet/superstore/assets/142443937/c4fc8cd4-a331-4464-878b-d5fbf74a9f90)

**Comment by supertestnet** [comment]
Thank you! I've added this to my todo list: https://github.com/supertestnet/superstore

**Comment by bordalix** [comment]
I was able to replicate this, but only if I had multiple products on my store.
While investigating this, I found a bug on how `data-num` was attributed to the "Add to cart" button.
After the [fix](https://github.com/supertestnet/superstore/pull/12) this bug disappeared.
Tested on my local machine.

**Comment by supertestnet** [comment]
> I was able to replicate this, but only if I had multiple products on my store. While investigating this, I found a bug on how `data-num` was attributed to the "Add to cart" button. After the [fix](https://github.com/supertestnet/superstore/pull/12) this bug disappeared. Tested on my local machine.

Reviewed and merged. Thank you for the pr!
