### ISSUE TITLE
Zero sats invoice?

### ISSUE THREAD

**Issue by GALLAY** [supertestnet/superstore#2]
Hi, I have added 2 products with a price of 0 sats. Made a test purchase and got an invoice with 0 sats. I sent more than 100 sats to the btc address shown in the invoice. The payment was confirmed on the blockchain, but no sats arrived under 'Manage Sales' until now after about a day. How can I get my sats back? ;))
https://supertestnet.github.io/superstore/?pubkey=02bfd76bc6973738e5757b372cf4d700a5fb729cb5c7b9083eaa909c70e1f0ff99&relay=wss://nostrue.com

**Comment by supertestnet** [comment]
You probably can't. If you sent the wrong amount of sats to the bitcoin address then it probably did not detect your payment so it did not send your whisper key to the merchant (i.e. you). You need the whisper key to get the money out so the money is probably gone forever.

**Comment by supertestnet** [comment]
Actually, did you get a receipt? If you got a receipt I can help you get your sats out

**Comment by supertestnet** [comment]
Ok if you *did* get a receipt that means your browser tried to fire off a notification about the whisper key to you, even though you overpaid. If it did that, then the money should be available to you. However, I had a sanity check in the code which was *supposed* to ignore malformed notifications, but it *also* -- by accident -- ignored orders whose total was 0. I fixed that in [this code change](https://github.com/supertestnet/superstore/commit/9c686562833ef2ae5eec8b4f62407e5f9708ca5d) so you should see your money show up now. Please let me know if it works for you.

**Comment by GALLAY** [comment]
Hi, I have not received a receipt.
But seems to have arrived correctly now, thank you!
![details](https://github.com/supertestnet/superstore/assets/7523322/6e79385e-c2a7-4ba2-8042-a2b986b0a50b)

**Comment by GALLAY** [comment]
Sorry, of course I got a receipt with a 'proof of payment' string but with total sum of 0 dollars. I have found my screenshot... ;)

**Comment by supertestnet** [comment]
Excellent, glad everything worked out
