### ISSUE TITLE
'Let users set the price' option overwrites all other fixed prices

### ISSUE THREAD

**Issue by GALLAY** [supertestnet/superstore#3]
One article saved with the option 'Let users set the price' (proposal price). After that, all other fixed price items (on the detail page) will be displayed with a 'Set an amount' price. You can test it here:
https://magicwebstore.xyz/?pubkey=02bfd76bc6973738e5757b372cf4d700a5fb729cb5c7b9083eaa909c70e1f0ff99

**Comment by supertestnet** [comment]
Thank you for this report. Fixed in [this commit](https://github.com/supertestnet/superstore/commit/91e7da81ebdf6c3b447aa55dbb08255d136aca41).
