### ISSUE TITLE
Error when adding a new product

### ISSUE THREAD

**Issue by GALLAY** [supertestnet/superstore#7]
Hi, The progress bar only runs through to the end when I change something in one of the 4 already existing products. Unfortunately, I cannot add a new product (tested with Brave).
And a question: wouldn't it be better to add a new product when creating it at the end of the list? Now it's inserted above the last product when I click on "Add another product".
![addnewproduct](https://github.com/supertestnet/superstore/assets/7523322/ab9e019d-d4dc-4f84-90cc-bfc5d576b6c5)

**Comment by GALLAY** [comment]
I had 4 products in the store. Three of them I could delete. The last one can not be deleted only overwrite(?).
Okay, so I overwrote this product and created a new (2nd) one. In Firefox this worked.
Then tried to save a 3rd product with Brave. Did not work.
Then the 3rd product in Firefox. Worked.

**Comment by supertestnet** [comment]
I think the latest update should fix your inability to create new items in brave. The site had a bug that made brave sometimes load outdated products into memory. An incorrect registry of products may have led to problems removing products. Please try again and let me know if this fixes your issue.

As for your question, "wouldn't it be better to add a new product when creating it at the end of the list?" that may be slightly more in line with user expectations, therefore offering a slightly improved UX, but it seems like a very minor improvement to me and is therefore not high on my priority list (or even on there at all)

As for your question, "The last one can not be deleted only overwrite(?)" That is correct. It doesn't make sense to me to have a store with 0 items, so I allow deleting all items except 1. But you can overwrite that item with a new one.

**Comment by GALLAY** [comment]
Thank you. Unfortunately, I get the same error with Brave. It hangs again on the 3rd product (relays updated).

**Comment by supertestnet** [comment]
Are you comfortable sharing a link to the admin page of a store where you cannot add a product as expected? I have not been able to reproduce the issue in brave or firefox

**Comment by GALLAY** [comment]
I'm using Brave with Debian 11. Maybe that already helps?
![brave](https://github.com/supertestnet/superstore/assets/7523322/ed04a319-733b-4ea1-b1f1-aa2147b1c034)
And let's see, maybe I send you a link by DM.

**Comment by supertestnet** [comment]
I'm running Debian 12 with Brave Version 1.52.129 Chromium: 114.0.5735.198 (Official Build)  (64-bit)

These versions are similar enough that I doubt the versioning is the problem, I bet there is some specific configuration of options on your store products that is giving you this issue. If you are okay with DMing me you can do so on several platforms.

On telegram I am @supertestnet 
On twitter I am @super_testnet

Or you can contact me on simplex with this address: https://simplex.chat/contact#/?v=1-2&smp=smp%3A%2F%2FenEkec4hlR3UtKx2NMpOUK_K4ZuDxjWBO1d9Y4YXVaA%3D%40smp14.simplex.im%2FPKUDx8YRypk5DAT2RazRhX-DDBjKVZtj%23%2F%3Fv%3D1-2%26dh%3DMCowBQYDK2VuAyEAvwl_zFcG_qYDvp80rgRToguicAIZ67C42vETRij_ZVw%253D%26srv%3Daspkyu2sopsnizbyfabtsicikr2s4r3ti35jogbcekhm3fsoeyjvgrid.onion

**Comment by GALLAY** [comment]
Tested around a bit. As far as I can see the problem in my Brave configuration is a Chrome extension (Deepl translator). Creating or changing products works when the extension is off. Issue can be closed.
![js-error](https://github.com/supertestnet/superstore/assets/7523322/82943f07-fab2-4d0e-8536-56a4a19ad206)
